name: FlagsBlock
version: 1.0.0-B2
description: Module that adds block flags to the Flags plugin.
author: Alshain01
website: http://dev.bukkit.org/bukkit-plugins/flags/
main: alshain01.FlagsBlock.FlagsBlock
depend: [Flags]